# Name of the workflow
name: scrap_bmkg

# Controls when the workflow will run
on:
  push:
    branches: main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      # langkah pertama install R
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      
      # langkah kedua update dan install library di ubuntu
      - run: |
          sudo apt-get update
          
      # berikutnya adalah install libraries yang dibutuhkan di R
      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::dplyr
            any::rvest
            any::httr
            any::tidyverse
      
      # set working directory
      - name: Check out repository
        uses: actions/checkout@v3

      # buat github action menjalankan skrip scrap_bmkg.R
      - name: Run skrip R
        run: Rscript -e 'source("scrap_bmkg.R")'
      
      # berikutnya commit dan push ke repo
      - name: Commit results
        run: |
          git config --local user.email "tasyaanisahrizqi@gmail.com"
          git config --local user.name "tasyaanisahrizqi"
          git add .
          git commit -m 'Data updated' || echo "No changes to commit"
          git push || echo "No changes to commit"
